export default AnalylticsConstant = {
    OPEN_APP : "OPEN_APP_IOS",
    PRODUCT_PAGE: "PRODUCT_PAGE_IOS",
    SPLASHSCREEN : "SPLASHSCREEN_IOS",
    LOGIN :"LOGIN_IOS",
    SIGN_UP : "SIGN_UP_IOS",
    LOG_OUT : "LOG_OUT_IOS",
    ADD_TO_WISHLIST : "ADD_TO_WISHLIST_IOS",
    REMOVE_WISHLIST : "ADD_TO_WISHLIST_IOS",
    ADD_TO_CART : "ADD_TO_CART_IOS",

   CART_EVENT : "CART_EVENT_IOS",
   DELETE_ITEM : "DELETE_ITEM_IOS",
   APPLY_VOUCHER : "APPLY_VOUCHER_IOS",
   DELETE_VOUCHER : "DELETE_VOUCHER_IOS",

   CHECKOUT_EVENT : "CHECKOUT_EVENT_IOS",
   SELECTED_PAYMENT_METHOD :"SELECTED_PAYMENT_METHOD_IOS",
   GO_FOR_GUEST_CHECKOUT : "GO_FOR_GUEST_CHECKOUT_IOS",
   SHIPPING_METHOD_VIEW:"SHIPPING_METHOD_VIEW",   
   SHIPPING_METHOD_SELECET:"SHIPPING_METHOD_SELECET_IOS",   
   PAYMENT_METHOD_VIEW : "PAYMENT_METHOD_VIEW_IOS",
   SELECTED_PAYMENT_METHOD : "SELECTED_PAYMENT_METHOD_IOS",

   ECOMMERCE_PURCHACE :"ECOMMERCE_PURCHACE",
   ECOMMERCE_PURCHACE_ORDER :"ECOMMERCE_PURCHACE_ORDER",

   CATALOG : "CATALOG",
   
   CATEGORY : "CATEGORY",
   PAGE_HOME : "PAGE_HOME",
   SEARCH : "SEARCH",
   SELLER_PRODUCT : "SELLER_PRODUCT",

    DEVICE_ID : "DEVICE_ID",
    DEVICE_NAME : "DEVICE_NAME",
    DEVICE_OS : "DEVICE_OS",
    ID:"id",
    NAME:"name",
    VARIATION:"Variation",
    METHOD : "METHOD"    
    
}