export default AnalylticsConstant = {
    OPEN_APP : "OPEN_APP_ANDROID",
    PRODUCT_PAGE: "PRODUCT_PAGE_Android",
    SPLASHSCREEN : "SPLASHSCREEN_ANDROID",
    LOGIN :"LOGIN_ANDROID",
    SIGN_UP : "SIGN_UP_ANDROID",
    LOG_OUT : "LOG_OUT_ANDROID",
    ADD_TO_WISHLIST : "ADD_TO_WISHLIST_ANDROID",
    REMOVE_WISHLIST : "ADD_TO_WISHLIST_ANDROID",
    ADD_TO_CART : "ADD_TO_CART_ANDROID",

   CART_EVENT : "CART_EVENT_ANDROID",
   DELETE_ITEM : "DELETE_ITEM_ANDROID",
   APPLY_VOUCHER : "APPLY_VOUCHER_ANDROID",
   DELETE_VOUCHER : "DELETE_VOUCHER_ANDROID",

   CHECKOUT_EVENT : "CHECKOUT_EVENT_ANDROID",
   SELECTED_PAYMENT_METHOD :"SELECTED_PAYMENT_METHOD_ANDROID",
   GO_FOR_GUEST_CHECKOUT : "GO_FOR_GUEST_CHECKOUT_ANDROID",
   SHIPPING_METHOD_VIEW:"SHIPPING_METHOD_VIEW",   
   SHIPPING_METHOD_SELECET:"SHIPPING_METHOD_SELECET_ANDROID",   
   PAYMENT_METHOD_VIEW : "PAYMENT_METHOD_VIEW_ANDROID",
   SELECTED_PAYMENT_METHOD : "SELECTED_PAYMENT_METHOD_ANDROID",

   ECOMMERCE_PURCHACE :"ECOMMERCE_PURCHACE",
   ECOMMERCE_PURCHACE_ORDER :"ECOMMERCE_PURCHACE_ORDER",

   CATALOG : "CATALOG",
   
   CATEGORY : "CATEGORY",
   PAGE_HOME : "PAGE_HOME",
   SEARCH : "SEARCH",
   SELLER_PRODUCT : "SELLER_PRODUCT",

    DEVICE_ID : "DEVICE_ID",
    DEVICE_NAME : "DEVICE_NAME",
    DEVICE_OS : "DEVICE_OS",
    ID:"id",
    NAME:"name",
    VARIATION:"Variation",
    METHOD : "METHOD"    
    
}