    export default {    
    WARNING : "Warning",
    UPDATE_WARNING : "Update Warning!",
    OOPS : "Oops!",
    NETWORK_ERROR : "Network Error.",
    SERVER_MAINTENANCE : "Server under maintenance.",
    OFFLINE_ERROR : "You are in Offline.",
    RETRY : "Retry",
    CANCEL :"Cancel",
    REQUIRED_FIELD : "Please fill the detail",
    URL_VALIDITY_REQUIRED :"Please check validity",
    PASSWORD_REQUIRED_FIELD : "Please fill the password",
    EMAIL_REQUIRED_FIELD : "Please enter valid email",
    PHONE_REQUIRED_FIELD : "Please enter valid phone number",
    PLEASE_WAIT : "Please Wait",
    LOADING : "Loading...",
    EXIT_APP_MSG :"Press again to exit from app",
    SOMETHING_WENT_WRONG : "SOMETHING WENT WRONG!!!",
    PRODUCT_SUCCESS_FULLY_UPDATED_MSG : "Product Successfully updated",

    NO_URL_ADDED_YET : "No URL added yet",
    NAME_EMPTY_ERROR : "Name should not be empty",
    RATING_EMPTY_ERROR : "Please add your Rating",
    MESSAGE_EMPTY_ERROR : "Message should not be empty",
    MESSAGE_NO_SORTING_OPTION : "No sorting option available.",
    UPDATE_TEXT : "Yes, Update it.",
    EMPTY_ADDRESS : "No Address Yet.",
    YES :"YES",

    DELETE_CART_ITEM_WARNING : "Do you want to remove this item from your cart?",
    DELETE_CART_WARNING : "Do you want to empty your cart?",
    
    DELETE_SELLER_PRODUCT_WARNING : "Do you want to delete this product?",

    ASK_OFFLINE_ADD_TO_CART_MSG : "Do you want to add this product in your offline cart? This Cart will sync whenever you are online and View Your Cart.",
    YES_ADD_TO_CART : "Yes",
    OFFLINE_CART_SUCCESS_MESSAGE : "Product has successfully added in your offline cart.",
    OFFLINE_CART_ERROR_MESSAGE : "Something went wrong.",
    OFFLINE_CART_MSG :"OFFLINE CART",
    ASK_USER_TO_ADD_OFFLINE_CART : "There are some items in your offline cart. Do you want to sync them with your Cart.",
    AFTER_SOME_TIME : "Ask Me Later",

    QUANTITY_EXCEED_ERROR : "Quantity should be less the 1000",

    CAMERA : "CAMERA",
    GALLERY : "GALLERY",
    SELECT_CHOICE : "Select Choice",
    UPDATE : "Update",
    PROFILE_IMAGE : "Profile Image",
    SELLER_LOGO : "Logo",
    PROFILE_BANNER : "Profile Banner",
    NO_FILE_SELECTED : "No File Selected.",
    UPLOAD_IMAGE : "UPLOAD",

    MORE_TITLE:"MORE",
    ACCOUNT_TITLE: "Account",
    DASHBOARD_TITLE: "Dashboard",
    HOME_TITLE: "Home",
    CATEGORY_TITLE: "Category",
    REGISTER_TITLE: "Create an Account", 
    LOGIN_TITLE: "Sign In with Email/User Name",
    CHECKOUT_AS_GUEST : "Checkout as a Guest",
    LOGOUT_TITLE: "Logout",
    CART_TITLE: "Cart",
    CHECKOUT_TITLE : "SHIPPING INFO",
    CHECKOUT_OPTIONS : "Checkout Options",
    MARKETPLACE_TITLE: " MarketPlace",
    PRODUCT_TITLE: "Products",
    ORDER_HISTORY: "Order History",
    ORDER_DETAIL: "Order Detail",
    ORDER_TITLE: "ORDER",
    DOWNLOAD_TITLE: "DOWNLOADS",
    TRANSACTION_TITLE: "TRANSACTIONS",
    TRANSACTION_DETAIL: "TRANSACTION DETAIL",
    SELLER_LIST_TITLE: "Seller List",
    SELLER_PROFILE_TITLE: "Seller Profile",
    SELLER_PRODUCT_TITLE : "Seller Products",
    ADD_NEW_PRODUCT : "Add Product",
    SELLER_ORDER_TITLE : "Seller Orders",
    SELLER_QUERY_LIST_TITLE : "All queries",
    ASK_TO_ADMIN: "Ask to Admin",
    ASK_QUERY : "ASK Query",
    ADDRESS_TITLE: "Address Book",
    ACCOUNT_DETAIL_TITLE: "Account Information",
    UPDATE_ADDRESS : "Edit Address",
    BACK : "BACK",
    NOTIFICATION : "Notification",

    PRODUCT_DESCRIPTION : "DESCRIPTION",
    PRODUCT_REVIEWS:"PRODUCT REVIEWS",
    PRODUCT_REVIEWS_DETAIL:"Review Detail",
    PRODUCT_REVIEWS_:"PRODUCT REVIEWS",
    VIEW_ALL_PRODUCT_REVIEWS:"VIEW ALL PRODUCT REVIEWS",
    ADDITIONAL_INFORMATION : "Additional Information",
    REVIEWER_NAME : "Review by",
    DATE : "Date",
    WRITE_REVIEWS : "WRITE A REVIEW",
    RECENT_REVIEW : "Recent Reviews",
    NO_REVIEW_MSG : "No review has found.",  
    ENTER_YOUR_MESSAGE : "Enter Your Message.",

    ///Sller Profile View////
    SELLER_PROFILE: " Seller Profile",
    SELLER_PROFILE_VIEW: " Seller Profile View",
    VIEW_PROFILE: "View Profile",
    PRICE: "PRICE",
    VALUE: "VALUE",
    QUALIY: "QUALITY",
    RECENT_PRODUCT_FROM_SELLER: "Recent Product from Seller",
    SELLER_INFO :"Seller Informations",
    CUSTOMER_INFO : "Customer Informations",
    SELLER_NAME : "Seller - ",

    EMPTY_SELLER_MSG: "No Seller has found !!!",
    SELLER_TOTAL_PRODUCTS: "Total Products",
    NO_ORDER_GENERATED : "No Order has generated !!!",
    NO_NOTIFICATION : "No Notification has found !!!",
    EMPTY_QUERY_MSG : "No query has Found !!!",
    EMPTY_SELLER_PRODUCT : "No product Found!!!",
    EMPTY_SELLER_TRANSACTION : "No transation Found!!!",
    ABOUT_SHOP : "About Shop",
    SOCIAL_PROFILE : "Social Profile",
    FACEBOOK_PROFILE : "Facebook Profile ID (optional)",
    TWITTER_PROFILE : "Twitter Profile ID (optional)",
    GOOGLE_PROFILE : "Google Plus ID (optional)",
    YOUTUBE_PROFILE : "Youtube Profile ID (optional)",
    LINKED_IN_PROFILE : "Linkedin Profile ID (optional)",
    PAYMENT_INFO : "Payment Information",
    YOUTUBE : "Youtube",
    LINKED_IN  : "Linkedin",
    GOOGLE  : "Google",
    TWITTER  : "Twitter",
    FACEBOOK  : "Facebook",

    TRANSACTION_DATE : "TRANSACTION DATE: ",
    TRANSACTION_TOTAL : "TRANSACTION TOTAL: ",
    TRANSACTION_ID :"TRANSACTION ID: ",
    TRANSACTION_ID_TITLE :"Transaction Id ",
    TRANSACTION_INFORMATION : "TRANSACTION INFORMATION",
    TRANSACTION_TYPE : "Type",
    TRANSACTION_METHOD : "Method",
    TOTAL_PRICE : "Total price",
    COMMISSION : "Commission",
    

    /// Seller DASHBOARD /////////
    LIFE_TIME_SALE : "Life Time Sale",
    TOTAL_PAYMENT : "Total Payment",
    REFUNDED_AMOUNT : "Refunded Amount",
    REMAINING_AMOUNT : "Remaining Amount",
    TOP_SELLING_PRODUCT : "TOP SELLING PRODUCTS",
    EMPTY_TOP_SELLING_PRODUCT : "No Top Selling Product Found.",

    RECENT_ORDER : "RECENT ORDERS",  
    EMPTY_RECENT_ORDER : "No recent order found.",  
    ORDER_ID : "Order Id #",
    ORDER_DATE_ : "Order Date : ",
    BILLING_EMAIL : "Billing Email : ",
    NAME: "Name : ",
    NAME_: "Name",
    TOTAL_ITEM_:  "Total Item : ",
    ORDER_TOTAL_ : "Order Total : ",
    ORDER_STATUS_ : "Order Status :",
    ORDER_STATUS : "Order Status",
    CUSTOMER_DETAIL : "CUSTOMER DETAIL",

    ////// Seller Product ADD////
    SELECT_SELLER_PRODUCT_TYPE : "Select Product Type",
    SELECET_CATEGORY :  "Select Categories",
    SELECETED_CATEGORY :  "Selected Categories",
    ERROR_NOT_SELECTED_CATEGORY : "Sorry, Please select product category(s).",
    PRODUCT_NAME : "Product Name",
    ABOUT_PRODUCT : "About Product",
    PRODUCT_THUMBNAIL : "Product Thumbnail",
    PRODUCT_SKU : "SKU",
    SKU_VALIDATION_ERROR: "Please validate SKU",
    PRODUCT_VIDEO: "Product Video",
    REGULAR_PRICE :"Regular Price",
    SALE_PRICE : "Sale Price",
    PRODUCT_SHORT_DESCRIPTION :"DETAIL",
    ERROR_SALE_PRICE : "Sale Price cannot be greater than or equal to Regular Price.",
    MANAGE_STOCK : "Manage Stock",
    ENABLE_STOCK_LABEL_MSG : "Enable stock management at product level",
    STOCK_QTY : "Stock Qty",
    ALLOW_BACK_ORDER : "Product Returns",
    STOCK_STATUS : "Stock Status",
    WEIGHT : "Weight (kg)",
    DIMENTIONS : "Dimensions (cm)",
    SHIPPING_CLASS  : "Shipping class",
    LENGTH : "Length",
    HEIGHT : "Height",
    WIDTH : "Width",
    NO_IMAGES_ADD_YET : "No image added yet.",
    NO_PRODUCT_MSG : "No product added yet",
    NO_SHIPPING_CALSS : "No Shipping Class.",
    NO_PRODUCT_FOUND_MSG : "No product found",

    DOWNLOADABLE_PRODUCT : "Downloadable Product",
    IMAGE_GALLERY : "Image Gallery",
    NEW_IMAGES : "New Images",
    ADD : "ADD NEW",
    ADD_MORE : "Add More",

    PRODUCT_URL : "Product URL",
    BUTTON_TEXT : "Button Text",
    EXTERNAL_LINK_AFFILIATE : "External/Affiliate",

    GROUPED_PRODUCT : "Grouped Product",
    UP_SELLES : "Upselles",
    CROSS_SELLES : "Cross-sells",


    SAVE : "SAVE",  
    EDIT_TITLE : "EDIT",
    INVENTORY:"Inventory",
    LINKED_PRODUCT : "Linked Product",
    ATTRIBUTE : "Attributes",
    PRODUCT_STATUS : "Product Status",
    ADD_PRODUCT_IMAGES : " Add product images",
    EDIT_INFO: "EDIT INFO",
    PRODUCT_AUCTION: "Product Auction",

    //////// ProductPAGE ////////
    QUANTITY : "QUANTITY",
    ADD_GROUP_ITEMS : "Add Group Items",
    RELATED_PRODUCT : "RELATED PRODUCT",
    PURCHASABLE_CHOICE_ERROR : "This product options is not purchaseable.\nPlease choose another.",
    PURCHASABLE_CONTACT_ERROR: "This product options is not purchaseable.\nPlease contact to us.",
    OUT_OF_STOCK_CONTACT_ERROR : "This product options is out of stock.\nPlease contact to us.",
    EMPTY_QUANTITY_ERROR : "Please choose the quantity of items.\nif you wish to add to your cart.",
    NO_ATTRIBUTE_SELECTED_ERROR : "Please select your options.",
    INSTOCK : 'IN STOCK',
    OUT_OF_STOCK : 'OUT OF STOCK',
    SUBMIT_REVIEW : "SUBMIT REVIEW FOR APPROVAL",
    YOUR_REVIEW : "Your Review",
    REVIEWS : "Reviews",
    REVIEW : "Review",
    ADD_YOUR_REVIEWS : "ADD YOUR REVIEW",
    UNITS : "Units",
    NO_REVIEW_ADDED_YET :  "No Review Yet",
    OFF : "OFF",
    OUT_OF_STOCK_QUANTITY_ADD : 'Product quantity is not enough.',
    SIMPLE_PRODUCT_OUT_OF_STOCK_CONTACT_ERROR : "The product is out of stock.\nPlease contact to us.",
    BACK_ORDER_MSG : "(can be backordered)",

    ///CART////
    QTY: "QTY",
    QTY_: "Qty : ",
    SELECT_QUANTITY: "Select quantity",
    SUBTOTAL: "Subtotal",
    SHIPPING_COST: "Shiiping Cost",
    SHIPPING: "Shipping",
    SHIPPING_COST :"Shipping Cost",
    SMALL_PRICE : "Price",
    TAX: "Tax",
    ADMIN_COMMISSION:"Admin_Commission",
    DISCOUNT: "Discount",
    ORDER_TOTAL: "Order Total",
    APPLY_DISCOUNT_CODE: "APPLY DISCOUNT CODE",
    ENTER_DISCOUNT_CODE: "Enter Discount Code",
    EMPTY_COUPON_CODE_ERROR : "Please add coupon code!!!",
    APPLY: "APPLY",
    PROCEED: "PROCEED",
    UPDATE_CART : "UPDATE CART",
    EMPTY_CART : "EMPTY CART",
    CONTINUE_SHOPPING : "CONTINUE SHOPPING",
    CART_EMPTY_MESSAGE : "No Items in your Cart !!! \nPlease add product in your Cart.",
    CART_EMPTY_TITLE : "EMPTY CART",
    AMMOUNT_TO_BE_PAID: "Amt. to be paid",
    PRICE_DETAIL: "PRICE DETAIL",
    REMOVE_ITEM : "REMOVE ITEM",
    REMOVE : "Remove",
    ADD_EDIT_ADDRESS : "ADD/EDIT ADDRESS",
    VIEW_ADDRESS : "VIEW ADDRESS",
    APPLIED_COUPON : "Applied Coupon",
    APPLIED_TAX : "Applied Tax",

    ADD_TO_CART : "ADD TO CART",
    VIEW_PRODUCT : "VIEW",
    BUY_NOW : "BUY NOW",
    
    // Checkout
    SHIPPING_METHOD_TITLE : "SHIPPING METHOD",
    PAYMENT_METHOD_TITLE : "PAYMENT METHOD",
    CHECKOUT_REVIEW_TITLE : "REVIEW AND PAYMENT",
    ORDER_PLACE_TITLE :"ORDER PLACE",
    SHIPPING_INFO : "SHIPPING INFO",
    MAKE_PAYMENT :"MAKE PAYMENT",
    PAYMENT : "PAYMENT",
    SHIPPING_METHODS : "SHIPPING METHODS",
    ITEMS : "ITEM(S)",
    PRODUCTS : "Products",

    // Address
    BILLING_ADDRESS : "BILLING ADDRESS",
    SHIPPING_ADDRESS : "SHIPPING ADDRESS",
    TELEPHONE_ : "Telephone :",

    /////  Search /////
    SEARCH_PLACEHOLDER_TEXT : 'Search for a product.',
    SEARCH_BUTTON_TEXT : 'Search',
    SEARCH_START_EMPTY_TEXT : 'Start your Search by typing above',
    SEARCH_EMPTY_TEXT_ERROR : 'You have search empty text',
    SEARCH_3_MORE_CHAR_MSG : "Please enter 3 or more characters",
    RESULT_FOUND : "Result found(s)",

    ////////////  Profile /////////
    Dashboard: "Dashboard",
    MARKETPLACE: "Marketplace",
    USER_NAME: "User Name",
    USER_NAME_EMAIL: "User Name/Email",
    EMAIL: "Email",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    VIEW_ALL : "View All",
    PASSWORD :"Password" ,
    NEW_PASSWORD : "New Password",
    OLD_PASSWORD : "Old Password",
    CONFIRMATION_PASSWORD : "Confirmation Password",
    BLANK_MSG : "(leave blank to leave unchanged)",
    SAVE_ACCOUNT : "Save Account",
    SHOP_NAME : "Shop Name",
    SHOP_URL : "Shop URL",
    PHONE_NUMBER :"Phone Number",
    EMAIL_ADDRESS : "Email Address",
    COMPANY_NAME : "Company name",
    STREET_ADDRESS : "Street Address",
    STREET_ADDRESS_2 : "Street Address 2",
    ADDRESS_LINE_1 : "Address Line 1",
    ADDRESS_LINE_2 : "Address Line 2",
    CITY : "City",
    ZIP_CODE : "Zip/PostalCode",
    TELEPHONE : "Telephone",
    COUNTRY : "Country",
    STATE : "State",
    SHIPPING_SAME_AS_BILLING : "Shipping same as Billing Address",
    SAVE_ADDRESS :"Save Address",

    I_AM_CUSTOMER : "I am a customer",
    I_AM_SELLER : "I am a Seller",
    VALIDATE : "Validate",

    SIGN_IN : "SIGN IN",
    SIGN_IN_OR_REGISTER : "SIGN IN OR REGISTER",
    OR:"-----------  OR  ------------",
    SIGN_IN_WITH_EMAIL : "SIGN IN WITH EMAIL/USER NAME",
    ASK_FOR_REGISTER : "If you are not a user, please create an account",
    ASK_FOR_LOGIN : "If you are already registered, please Sign In",
    SIGN_UP : " SIGN UP",
    CREATE_AN_ACCOUNT : "CREATE AN ACCOUNT",
    SUCCESSFULL_LOGIN_MSG : "You have successfully logged in.",
    SUCCESSFULL_REGISTER_MSG : "You have successfully registered.",
    PASSWORD_ERROR_MSG : "Password should not be empty",
    EMAIL_EROR_MSG : "Please enter valid email",
    EMAIL_USER_NAME_EROR_MSG : "Please enter valid email/user name",
    ASK_LOGOUT_MSG : "Do you want to Logout?",
    ASK_FOR_FORGOT_PASSWORD : "Lost your password? Please enter your username or email address. You will receive a link to create a new password via email.",
    RESET_PASSWORD : "Reset Password",
    FORGOT_PASSWORD : "Lost your password?",
    YES_LOGOUT : "YES, Logout",
    SEARCH :"Search",
    VALIDATE :"Validate",
    SELECT_SHIPPING_ERROR_MSG : "Please select a shipping method.",
    SELECT_SHIPPING_ERROR_MSG_OR_CONTACT_WITH_US : "\nPlease update your shipping address or contact with us.",
    SELECT_PAYMENT_METHOD_ERROR_MSG : "Please select a payment method.",
    ORDER_SUCCESS_MSG : "Your order has successfully done",

    ITEM_ORDERED : "ITEM(S) ORDERED",
    BASED_ON : "Based on",
    VIEW_MORE : "View more",
    ORDER_CREATED_ON : "Placed on",
    NO_MORE_PRODUCT_FOUND : "No more product found.",

    OLD_PASSWORD_ERROR : "Please enter old Password.",
    NEW_PASSWORD_ERROR : "Please enter new Password.",
    CONFIRM_PASSWORD_MATCH_ERROR : "Confirm password should be match.",
    DATE_ : "Date : ",
    SUBJECT_ : "Subject : ",
    SUBJECT : "Subject",
    MESSAGE_ : "Message : ",
    MESSAGE : "Message",
    ENTER_YOUR_QUERY :"Enter Your Query",
    SUBJECT_ERROR_MSG :"Subject should not be an empty",
    MESSAGE_ERROR_MSG :"Message should not be an empty",
    SEND_MESSAGE : "Send Message",
    CHOOSE_OPTIONS : "SELECT OPTIONS",
    DETAIL:"ORDER DETAIL",
    REORDER:"REORDER",
    SHIPPING_AND_PAYMENT_INFORMATION : "SHIPPING AND PAYMENT INFORMATION",
    BY : "By",
    SALE :"SALE",
    CHOOSE_A_PRODUCT_TO_REVIEW:"Choose a Product to Review",
    REMAINING_DOWNLOADS :"REMAINING DOWNLOADS : ",
    DOWNLOAD :"DOWNLOAD",
    PRODUCT : "PRODUCT",
    PERMISSION_REQUEST :"Permission Request!!",
    WRITE_PERMISSION_MSG : "Please allow WRITE PERMISSION to download file.",
    AUDIO_PERMISSION_MSG : "Please allow AUDIO PERMISSION to voice recognization.",
    ASK_ME_LATTER : "Ask Me Later",
    OK :"OK",
    USER_PERMISSION_DENIED:"Permission denied",
    DOWNLOADING_STATUS :"Downloading complete",

    SHOW_ALL_CATEGORY : "SHOW ALL CATEGORY",
    EXTERNAL_LINKS :"WEBSITE LINKS",
    SORT:"SORT",
    LIST : "LIST",
    GRID:"GRID",

    // Dashboard//
    RECENT_ORDER_TITLE : "Recent Orders",
    REVIEWS_TITLE : "Review(s)",
    VIEW_ALL_ORDERS : "VIEW ALL ORDERS",
    IMAGE_NOT_UPDATE : "Image not added yet for profile banner/logo.",
    YOUR_REVIEWS : "YOUR REVIEWS",

    ORDER_PLACE_MSG : "THANKS FOR PURCHASE",
    YOUR_ORDER_NUMBER_IS : "Your order number is: ",
    OORDER_PLACE_SUBTITLE : "We will email you an order confirmation with detail.",

    LOGIN_AUTHENTICATION_TITLE : "Login Authentication",
    SCAN_YOUR:"Scan your ",
    SCAN_BIOMETRIC_TEXT : (biometric) => (`Scan your ${biometric} on the\ndevice scanner to continue`),
    ASK_FOR_ADD_FINGRE_PRINT :(biometric)=>( `Do you want to add your ${biometric} for login?` ),
    ASK_FOR_UPDATE_FINGRE_PRINT :(biometric)=>`Do you want to replace previous credentials with these ones, for  ${biometric} authentication?`,
    SPACE : " ",
    COLLON : " : ",

    LOCATION_ACCESS_TITLE : "Location Permission",
    LOCATION_ACCESS_MESSAGE: "App needs access your Location",
  };
